---
- name: restart etcd
  command: /bin/true
  notify:
    - reload systemd
    - start etcd
    - wait for etcd up
    - reload etcd
    - wait for etcd up

- name: reload systemd
  command: systemctl daemon-reload
  when: ansible_service_mgr == "systemd"

- name: wait for etcd up
  wait_for:
    host: 127.0.0.1
    port: 2379
    delay: 5

- name: reload etcd
  service:
    name: etcd
    state: "{{ 'restarted' if etcd_deployment_type == 'host' else 'reloaded' }}"


