---
- set_fact: etcd_access_address="{{ access_ip | default(ip | default(ansible_default_ipv4['address'])) }}"
- set_fact: etcd_peer_url="http://{{ etcd_access_address }}:2380"
- set_fact: etcd_client_url="http://{{ etcd_access_address }}:2379"
- set_fact:
    etcd_access_addresses: |-
      {% for item in groups['etcd'] -%}
        http://{{ hostvars[item].etcd_access_address }}:2379{% if not loop.last %},{% endif %}
      {%- endfor %}
- set_fact:
    is_etcd_master: "{{ inventory_hostname in groups['etcd'] }}"
- set_fact:
   etcd_member_name: |-
      {% if is_etcd_master %}
      {%   for host in groups['etcd'] %}
      {%     if inventory_hostname == host %}{{"etcd"+loop.index|string }}{% endif %}
      {%-   endfor %}
      {% else -%}
      etcd-proxy
      {%- endif %}
- set_fact:
    etcd_after_v3: etcd_version | version_compare("v3.0.0", ">=")
- set_fact:
    etcd_container_bin_dir: "{% if etcd_after_v3 %}/usr/local/bin/{% else %}/{% endif %}"
